name: CI
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      -
        name: Test
        run: echo ${ GITHUB_REF_NAME//\//_ }