name: Sandbox Actions

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check_for_changes:
    runs-on: ubuntu-latest
    outputs:
      sql-cache-hit: ${{ steps.cache-sql.outputs.cache-hit }}
      root-cache-hit: ${{ steps.cache-sql.outputs.cache-root }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Cache sql directory
        id: cache-sql
        uses: actions/cache@v3.3.2
        with:
          path: ~/sql
          key: sql-${{ hashFiles('sql/') }}
          restore-keys: |
            sql-${{ hashFiles('sql/') }}

      - name: Cache root
        id: cache-root
        uses: actions/cache@v3.3.2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            .github/actions/setup/action.yaml
            .github/workflows/run.yaml
            fuga.sql
          key: root-${{ hashFiles('.github/workflows/run.yaml', '.github/actions/setup/action.yaml', 'fuga.sql') }}
          restore-keys: |
            root-${{ hashFiles('.github/workflows/run.yaml', '.github/actions/setup/action.yaml', 'fuga.sql') }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  plan:
    needs: check_for_changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.1

      - name: Setup
        id: setup
        uses: ./.github/actions/setup
        with:
          sql-cache-hit: ${{ needs.check_for_changes.outputs.sql-cache-hit }}
          root-cache-hit: ${{ needs.check_for_changes.outputs.root-cache-hit }}

      - name: Plan
        if: steps.setup.outputs.skip != 'true'
        run: echo "SQL Plan"

  apply:
    if: github.ref == 'refs/heads/main'
    needs:
      - check_for_changes
      - plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.1

      - name: Setup
        id: setup
        uses: ./.github/actions/setup
        with:
          sql-cache-hit: ${{ needs.check_for_changes.outputs.sql-cache-hit }}
          root-cache-hit: ${{ needs.check_for_changes.outputs.root-cache-hit }}

      - name: Run
        if: steps.setup.outputs.skip != 'true'
        run: echo "Run SQL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
