name: GitHub Actions Demo
on: [push]
jobs:
  diff:
    runs-on: ubuntu-latest
    strategy:  
      matrix:  
        directory:  
          - manualsql  
          - sql  
    permissions:
      id-token: write
      contents: read
    outputs:  
      matrix: ${{ steps.set-matrix.outputs.matrix }}  
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v40.2.2
        with:
          files: |
            manualsql/**
      - name: List all changed files
        id: changed-files
        run: |
          for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Run AWS CLI
        run: |
          for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
            echo '{ "filePath": "$file" }'
          done
      - name: Determine changed directories  
        id: set-matrix  
        run: |  
          echo "::set-output name=matrix::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | \
          grep -E '^(Alice|Bob)/' | awk -F/ '{print $1}' | sort -u | jq -R -s -c 'split("\n")[:-1]')"  
      - name: Terraform Init and Plan  
        run: |
          echo ${{ steps.set-matrix.outputs.matrix }}
          echo ${{ matrix.directory }}
          echo ${{github.event.before}}
          echo ${{github.event.after}}
