name: GitHub Actions Demo
on: [push]
jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v29
        with:
          files: |
            sql/**
      - name: List all changed files
        id: changed-files
        uses: tj-actions/changed-files@v29
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
